### ISSUE TITLE
PFImageView build error with Parse SDK 1.6.3

### ISSUE THREAD

**Issue by jcnes** [hathway/Parse-PromiseKit#3]
When trying to incorporate Parse-PromiseKit into a project with the most recent SDK (1.6.3 at time of this writing), you'll get an error that it "Cannot find interface declaration for 'PFImageView'; did you mean 'UIImageView'?" It looks like ParseUI.framework is now a dependency. Adding that framework to my Podfile and adding <ParseUI.h> to Parse+PromiseKit.h eliminated the error.

**Comment by djtarazona** [comment]
It definitely is supposed to be `PFImageView`.  Parse recently separated out UI elements into a separate pod.

So it worked once you added ParseUI?  What changes did you make to Parse+PromiseKit.h?  I assuming you just imported the PFImageView.h header?

**Comment by jcnes** [comment]
No code changes needed. I think if ParseUI is added as a dependency in the podspec and  <ParseUI.h> is imported at the top of Parse+PromiseKit.h, everything will be fine again.

**Comment by elaygl** [comment]
Same in here.
Just needed to add the dependency and import in the header.

**Comment by tzapu** [comment]
this can now be closed
